# Generated by Django 4.1.1 on 2022-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                # ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
