# Generated by Django 4.1.1 on 2022-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_details',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='patient_details',
            name='bloogroup',
            field=models.CharField(blank=True, default=None, max_length=14),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='taluk',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
