# Generated by Django 4.1.1 on 2022-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patient_details_bloogroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='bloogroup',
            field=models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=14),
        ),
    ]
