# Generated by Django 4.1.1 on 2022-10-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patient_details_bloogroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_details',
            old_name='bloogroup',
            new_name='bloodgroup',
        ),
    ]
