# Generated by Django 4.1.1 on 2022-10-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_patient_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
    ]
