# Generated by Django 4.1.1 on 2022-10-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_remove_doctor_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='DEFAULT VALUE', max_length=128),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='DEFAULT VALUE', max_length=250),
        ),
    ]
