# Generated by Django 4.1.1 on 2022-10-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_rename_contact_number_doctor_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='', max_length=250),
        ),
    ]
