# Generated by Django 4.1.1 on 2022-10-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_rename_contact_number_receptionist_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('symptoms', models.TextField(max_length=200)),
                ('prescribed_drug', models.TextField(max_length=200)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('signed_by', models.CharField(max_length=100)),
                ('date', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
