# Generated by Django 4.1.1 on 2022-10-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_rename_prescription_recommended_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_history',
            old_name='patient_id',
            new_name='id_no',
        ),
        migrations.AddField(
            model_name='patient_history',
            name='paid_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
