# Generated by Django 4.1.1 on 2022-11-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0012_staffdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
