# Generated by Django 4.1.1 on 2022-11-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0013_staffdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
