# Generated by Django 4.1.1 on 2022-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_receptionist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_med',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
