# Generated by Django 4.1.1 on 2022-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('drug', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=500)),
                ('mfg_date', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unitprice', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
    ]
