# Generated by Django 4.1.1 on 2022-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='unitprice',
            field=models.CharField(max_length=50),
        ),
    ]
