# Generated by Django 4.1.1 on 2022-10-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_token_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
