# Generated by Django 4.1.1 on 2022-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='serial_no',
            field=models.CharField(max_length=20),
        ),
    ]
