# Generated by Django 4.1.1 on 2022-10-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_bill_quantity_alter_bill_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='name_of_drugs',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='serial_no',
        ),
    ]
