# Generated by Django 4.1.1 on 2022-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_remove_bill_amount_remove_bill_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=20)),
                ('name_of_drugs', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=100)),
                ('expiry', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
