# Generated by Django 4.1.1 on 2022-11-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onlinebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('select_day', models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('select_time', models.CharField(choices=[('8.00PM to 8.45PM', '8.00PM to 8.45PM'), ('9.00PM to 9.45PM', '9.00PM to 9.45PM')], max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
