# Generated by Django 4.1.1 on 2022-11-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('token_no', models.IntegerField()),
                ('op_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('registration_fee', models.IntegerField()),
                ('consultation_fee', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cash', models.CharField(max_length=100)),
                ('billed_by', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
    ]
